function var_der=var_der(phi)
global S1 xi
grad_4=(grad_x(phi).^2+grad_y(phi).^2+grad_z(phi).^2).^2+1e-9;
H_x=16*xi*(grad_x(phi).*(grad_x(phi).^2.*grad_y(phi).^2+grad_x(phi).^2.*grad_z(phi).^2 ...
    -grad_y(phi).^4-grad_z(phi).^4))./grad_4;
H_y=16*xi*(grad_y(phi).*(grad_y(phi).^2.*grad_z(phi).^2+grad_x(phi).^2.*grad_y(phi).^2 ...
    -grad_x(phi).^4-grad_z(phi).^4))./grad_4;
H_z=16*xi*(grad_z(phi).*(grad_x(phi).^2.*grad_z(phi).^2+grad_y(phi).^2.*grad_z(phi).^2 ...
    -grad_x(phi).^4-grad_y(phi).^4))./grad_4;
var_der=grad_x(fun_kappa(phi).*H_x)+...
+grad_y(fun_kappa(phi).*H_y)+...    
+grad_z(fun_kappa(phi).*H_z)+...
+grad_x(fun_kappa(phi).^2.*grad_x(phi))+grad_y(fun_kappa(phi).^2.*grad_y(phi))+grad_z(fun_kappa(phi).^2.*grad_z(phi));
end