%%相场右端项
function z = fun_rhs1(x,y,t)
global tau xi m lamda epsilon
        z_x= cos(x).*cos(y).*cos(t);
        z_y= -sin(x).*sin(y).*cos(t);        
        kappa=(1-3*xi)*(1+4*xi/(1-3*xi)*(z_x.^4+z_y.^4)./(z_x.^2+z_y.^2).^2);
        z_exact=sin(x).*cos(y).*cos(t);
        z_t=-sin(x).*cos(y).*sin(t);
        H_1=16*xi*(z_x.*(z_x.^2.*z_y.^2-z_y.^4))./((z_x.^2+z_y.^2).^2);
        H_2=16*xi*(z_y.*(z_x.^2.*z_y.^2-z_x.^4))./((z_x.^2+z_y.^2).^2);
        z_1=kappa.^2.*z_x+kappa.*H_1;
        z_2=kappa.^2.*z_y+kappa.*H_2;
        z_1_x= 2.*cos(t).*cos(x).*cos(y).*(3.*xi - 1).^2.*((4.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) - 1).*((4.*xi.*(4.*cos(t).^4.*cos(x).*sin(x).^3.*sin(y).^4 - 4.*cos(t).^4.*cos(x).^3.*cos(y).^4.*sin(x)))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) + (8.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4).*(2.*cos(t).^2.*cos(x).*cos(y).^2.*sin(x) - 2.*cos(t).^2.*cos(x).*sin(x).*sin(y).^2))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^3)) - cos(t).*cos(y).*sin(x).*(3.*xi - 1).^2.*((4.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) - 1).^2 + (16.*xi.*cos(t).*cos(y).*sin(x).*(cos(t).^4.*sin(x).^4.*sin(y).^4 - cos(t).^4.*cos(x).^2.*cos(y).^2.*sin(x).^2.*sin(y).^2).*(3.*xi - 1).*((4.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) - 1))./(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2 - (16.*xi.*cos(t).*cos(x).*cos(y).*(cos(t).^4.*sin(x).^4.*sin(y).^4 - cos(t).^4.*cos(x).^2.*cos(y).^2.*sin(x).^2.*sin(y).^2).*(3.*xi - 1).*((4.*xi.*(4.*cos(t).^4.*cos(x).*sin(x).^3.*sin(y).^4 - 4.*cos(t).^4.*cos(x).^3.*cos(y).^4.*sin(x)))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) + (8.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4).*(2.*cos(t).^2.*cos(x).*cos(y).^2.*sin(x) - 2.*cos(t).^2.*cos(x).*sin(x).*sin(y).^2))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^3)))./(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2 - (16.*xi.*cos(t).*cos(x).*cos(y).*(3.*xi - 1).*((4.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) - 1).*(4.*cos(t).^4.*cos(x).*sin(x).^3.*sin(y).^4 + 2.*cos(t).^4.*cos(x).*cos(y).^2.*sin(x).^3.*sin(y).^2 - 2.*cos(t).^4.*cos(x).^3.*cos(y).^2.*sin(x).*sin(y).^2))./(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2 - (32.*xi.*cos(t).*cos(x).*cos(y).*(cos(t).^4.*sin(x).^4.*sin(y).^4 - cos(t).^4.*cos(x).^2.*cos(y).^2.*sin(x).^2.*sin(y).^2).*(3.*xi - 1).*((4.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) - 1).*(2.*cos(t).^2.*cos(x).*cos(y).^2.*sin(x) - 2.*cos(t).^2.*cos(x).*sin(x).*sin(y).^2))./(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^3;
        z_1_y=  (16.*xi.*cos(t).*cos(y).*sin(x).*(cos(t).^4.*cos(x).^4.*cos(y).^4 - cos(t).^4.*cos(x).^2.*cos(y).^2.*sin(x).^2.*sin(y).^2).*(3.*xi - 1).*((4.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) - 1))./(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2 - 2.*cos(t).*sin(x).*sin(y).*(3.*xi - 1).^2.*((4.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) - 1).*((4.*xi.*(4.*cos(t).^4.*cos(y).*sin(x).^4.*sin(y).^3 - 4.*cos(t).^4.*cos(x).^4.*cos(y).^3.*sin(y)))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) + (8.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4).*(2.*cos(t).^2.*cos(x).^2.*cos(y).*sin(y) - 2.*cos(t).^2.*cos(y).*sin(x).^2.*sin(y)))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^3)) - cos(t).*cos(y).*sin(x).*(3.*xi - 1).^2.*((4.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) - 1).^2 + (16.*xi.*cos(t).*sin(x).*sin(y).*(cos(t).^4.*cos(x).^4.*cos(y).^4 - cos(t).^4.*cos(x).^2.*cos(y).^2.*sin(x).^2.*sin(y).^2).*(3.*xi - 1).*((4.*xi.*(4.*cos(t).^4.*cos(y).*sin(x).^4.*sin(y).^3 - 4.*cos(t).^4.*cos(x).^4.*cos(y).^3.*sin(y)))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) + (8.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4).*(2.*cos(t).^2.*cos(x).^2.*cos(y).*sin(y) - 2.*cos(t).^2.*cos(y).*sin(x).^2.*sin(y)))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^3)))./(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2 - (16.*xi.*cos(t).*sin(x).*sin(y).*(3.*xi - 1).*((4.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) - 1).*(4.*cos(t).^4.*cos(x).^4.*cos(y).^3.*sin(y) - 2.*cos(t).^4.*cos(x).^2.*cos(y).*sin(x).^2.*sin(y).^3 + 2.*cos(t).^4.*cos(x).^2.*cos(y).^3.*sin(x).^2.*sin(y)))./(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2 + (32.*xi.*cos(t).*sin(x).*sin(y).*(cos(t).^4.*cos(x).^4.*cos(y).^4 - cos(t).^4.*cos(x).^2.*cos(y).^2.*sin(x).^2.*sin(y).^2).*(3.*xi - 1).*((4.*xi.*(cos(t).^4.*cos(x).^4.*cos(y).^4 + cos(t).^4.*sin(x).^4.*sin(y).^4))./((3.*xi - 1).*(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^2) - 1).*(2.*cos(t).^2.*cos(x).^2.*cos(y).*sin(y) - 2.*cos(t).^2.*cos(y).*sin(x).^2.*sin(y)))./(cos(t).^2.*cos(x).^2.*cos(y).^2 + cos(t).^2.*sin(x).^2.*sin(y).^2).^3;
        zz=z_1_x+z_1_y;
        z_f =(1/(epsilon^2)*z_exact.*(z_exact.^2 - 1));
        z_u=lamda/epsilon*(1-z_exact.^2).^2.*cos(x).*sin(y).*cos(t);
        z= tau*z_t-zz+z_f+z_u;
    end